// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_pos/test/data/repositories/transaction_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_pos/core/common/result.dart' as _i5;
import 'package:flutter_pos/core/services/connectivity/ping_service.dart'
    as _i2;
import 'package:flutter_pos/data/datasources/local/queued_action_local_datasource_impl.dart'
    as _i9;
import 'package:flutter_pos/data/datasources/local/transaction_local_datasource_impl.dart'
    as _i4;
import 'package:flutter_pos/data/datasources/remote/transaction_remote_datasource_impl.dart'
    as _i8;
import 'package:flutter_pos/data/models/queued_action_model.dart' as _i10;
import 'package:flutter_pos/data/models/transaction_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePingData_0 extends _i1.SmartFake implements _i2.PingData {
  _FakePingData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPingService extends _i1.Mock implements _i2.PingService {
  MockPingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i3.Future<void> startPing({
    String? host = '8.8.8.8',
    int? count,
    int? interval = 1,
    int? maxPingLatencyTolerance = 400,
    int? pingLatencyToleranceCount = 3,
    int? maxLines = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startPing, [], {
              #host: host,
              #count: count,
              #interval: interval,
              #maxPingLatencyTolerance: maxPingLatencyTolerance,
              #pingLatencyToleranceCount: pingLatencyToleranceCount,
              #maxLines: maxLines,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(dynamic Function(List<int>, List<String>)? listener) =>
      super.noSuchMethod(
        Invocation.method(#addListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(dynamic Function(List<int>, List<String>)? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void clearListeners() => super.noSuchMethod(
    Invocation.method(#clearListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void addConnectionStatusListener(dynamic Function(bool)? listener) =>
      super.noSuchMethod(
        Invocation.method(#addConnectionStatusListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeConnectionStatusListener(dynamic Function(bool)? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeConnectionStatusListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void clearConnectionStatusListeners() => super.noSuchMethod(
    Invocation.method(#clearConnectionStatusListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopPing() => super.noSuchMethod(
    Invocation.method(#stopPing, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.PingData parsePingLine(String? line) =>
      (super.noSuchMethod(
            Invocation.method(#parsePingLine, [line]),
            returnValue: _FakePingData_0(
              this,
              Invocation.method(#parsePingLine, [line]),
            ),
          )
          as _i2.PingData);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TransactionLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionLocalDatasourceImpl extends _i1.Mock
    implements _i4.TransactionLocalDatasourceImpl {
  MockTransactionLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.Result<int>> createTransaction(
    _i6.TransactionModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i7.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#createTransaction, [transaction]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<void>> updateTransaction(
    _i6.TransactionModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateTransaction, [transaction]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteTransaction, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<_i6.TransactionModel?>> getTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [id]),
            returnValue: _i3.Future<_i5.Result<_i6.TransactionModel?>>.value(
              _i7.dummyValue<_i5.Result<_i6.TransactionModel?>>(
                this,
                Invocation.method(#getTransaction, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i6.TransactionModel?>>);

  @override
  _i3.Future<_i5.Result<List<_i6.TransactionModel>>> getAllUserTransactions(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserTransactions, [userId]),
            returnValue:
                _i3.Future<_i5.Result<List<_i6.TransactionModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i6.TransactionModel>>>(
                    this,
                    Invocation.method(#getAllUserTransactions, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<List<_i6.TransactionModel>>>);

  @override
  _i3.Future<_i5.Result<List<_i6.TransactionModel>>> getUserTransactions(
    String? userId, {
    String? orderBy = 'createdAt',
    String? sortBy = 'DESC',
    int? limit = 10,
    int? offset,
    String? contains,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserTransactions,
              [userId],
              {
                #orderBy: orderBy,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
                #contains: contains,
              },
            ),
            returnValue:
                _i3.Future<_i5.Result<List<_i6.TransactionModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i6.TransactionModel>>>(
                    this,
                    Invocation.method(
                      #getUserTransactions,
                      [userId],
                      {
                        #orderBy: orderBy,
                        #sortBy: sortBy,
                        #limit: limit,
                        #offset: offset,
                        #contains: contains,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<List<_i6.TransactionModel>>>);
}

/// A class which mocks [TransactionRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRemoteDatasourceImpl extends _i1.Mock
    implements _i8.TransactionRemoteDatasourceImpl {
  MockTransactionRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.Result<int>> createTransaction(
    _i6.TransactionModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i7.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#createTransaction, [transaction]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<void>> updateTransaction(
    _i6.TransactionModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateTransaction, [transaction]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteTransaction, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<_i6.TransactionModel?>> getTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [id]),
            returnValue: _i3.Future<_i5.Result<_i6.TransactionModel?>>.value(
              _i7.dummyValue<_i5.Result<_i6.TransactionModel?>>(
                this,
                Invocation.method(#getTransaction, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i6.TransactionModel?>>);

  @override
  _i3.Future<_i5.Result<List<_i6.TransactionModel>>> getAllUserTransactions(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserTransactions, [userId]),
            returnValue:
                _i3.Future<_i5.Result<List<_i6.TransactionModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i6.TransactionModel>>>(
                    this,
                    Invocation.method(#getAllUserTransactions, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<List<_i6.TransactionModel>>>);

  @override
  _i3.Future<_i5.Result<List<_i6.TransactionModel>>> getUserTransactions(
    String? userId, {
    String? orderBy = 'createdAt',
    String? sortBy = 'DESC',
    int? limit = 10,
    int? offset,
    String? contains,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserTransactions,
              [userId],
              {
                #orderBy: orderBy,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
                #contains: contains,
              },
            ),
            returnValue:
                _i3.Future<_i5.Result<List<_i6.TransactionModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i6.TransactionModel>>>(
                    this,
                    Invocation.method(
                      #getUserTransactions,
                      [userId],
                      {
                        #orderBy: orderBy,
                        #sortBy: sortBy,
                        #limit: limit,
                        #offset: offset,
                        #contains: contains,
                      },
                    ),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<List<_i6.TransactionModel>>>);
}

/// A class which mocks [QueuedActionLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueuedActionLocalDatasourceImpl extends _i1.Mock
    implements _i9.QueuedActionLocalDatasourceImpl {
  MockQueuedActionLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.Result<int>> createQueuedAction(
    _i10.QueuedActionModel? queue,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createQueuedAction, [queue]),
            returnValue: _i3.Future<_i5.Result<int>>.value(
              _i7.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#createQueuedAction, [queue]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<int>>);

  @override
  _i3.Future<_i5.Result<void>> deleteQueuedAction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteQueuedAction, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteQueuedAction, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<_i10.QueuedActionModel?>> getQueuedAction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQueuedAction, [id]),
            returnValue: _i3.Future<_i5.Result<_i10.QueuedActionModel?>>.value(
              _i7.dummyValue<_i5.Result<_i10.QueuedActionModel?>>(
                this,
                Invocation.method(#getQueuedAction, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i10.QueuedActionModel?>>);

  @override
  _i3.Future<_i5.Result<List<_i10.QueuedActionModel>>>
  getAllUserQueuedAction() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserQueuedAction, []),
            returnValue:
                _i3.Future<_i5.Result<List<_i10.QueuedActionModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i10.QueuedActionModel>>>(
                    this,
                    Invocation.method(#getAllUserQueuedAction, []),
                  ),
                ),
          )
          as _i3.Future<_i5.Result<List<_i10.QueuedActionModel>>>);
}
