// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6xqlyTuo56MkqcjgqDi7abWwNi1EBh6c',
    appId: '1:406037321591:web:153217cdc34efce3a3b372',
    messagingSenderId: '406037321591',
    projectId: 'flutter-pos-478ed',
    authDomain: 'flutter-pos-478ed.firebaseapp.com',
    storageBucket: 'flutter-pos-478ed.appspot.com',
    measurementId: 'G-CLMBZZ5W42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA67wagaW8U8yRKDMx5W5f2S0IPDTlVQSg',
    appId: '1:406037321591:android:dd6f394a021c2220a3b372',
    messagingSenderId: '406037321591',
    projectId: 'flutter-pos-478ed',
    storageBucket: 'flutter-pos-478ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkTI6SME6YjVEUYVS7hCqHlyhuAuQVNYk',
    appId: '1:406037321591:ios:fae2602173cc9368a3b372',
    messagingSenderId: '406037321591',
    projectId: 'flutter-pos-478ed',
    storageBucket: 'flutter-pos-478ed.appspot.com',
    iosBundleId: 'elriztechnology.com.flutterPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkTI6SME6YjVEUYVS7hCqHlyhuAuQVNYk',
    appId: '1:406037321591:ios:0d1bbcb3b019b127a3b372',
    messagingSenderId: '406037321591',
    projectId: 'flutter-pos-478ed',
    storageBucket: 'flutter-pos-478ed.appspot.com',
    iosBundleId: 'elriztechnology.com.flutterPos.RunnerTests',
  );
}
